"""empty message

Revision ID: 24df680eb6d3
Revises: 886aeec9a4e4
Create Date: 2020-06-16 00:41:59.790529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24df680eb6d3'
down_revision = '886aeec9a4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
